### ISSUE TITLE
Surprising behavior for option.Option.Some(None)

### ISSUE THREAD

**Issue by mrwizard82d1** [MaT1g3R/option#5]
I was learning this package to use in my own work. I was surprised by the behavior of this test:

```
    def test_ctor_some_but_none():
        sut = option.Some(None)
        # assert_that(sut.is_none)
        assert_that(sut.is_some)
```

I'll be the first to admit that I do not fully understand the expectations for an `Option` type, but I expected `option.Some(None)` to behave similarly to `option.maybe(None)`.

What is the reason for this choice?

**Comment by homeworkprod** [comment]
See https://github.com/dry-python/returns/issues/314 for a similar discussion.

While it might be justifiable to want to represent `Some(None)`, it certainly is confusing when looking at it from a Java background/perspective.

I'm still unsure what would be the best thing to do.

**Comment by MaT1g3R** [comment]
@mrwizard82d1 The reason for this choice is that I wanted `Some` to behave like a data constructor, which means whatever you put in it will not be modified.

This is mostly a stylistic choice, but when I originally developed this library, I used Scala in my day job, and this behaviour is consistent with Scala.

Now one could argue `Some(None)` is more correct if you look at it from a Haskell point of view, which I personally am not too concerned with here.

**Comment by mrwizard82d1** [comment]
Thanks, Matt. I appreciate the response and rationale.

Have a great day!
